package com.lkjmc.common.workflow;

public enum WorkflowSignal {
    SAVE_REQUESTED,
    SAVE_ACKNOWLEDGED,
    LOAD_REQUESTED,
    PROFILE_APPLIED,
    DELIVERY_REQUESTED,
    DELIVERY_ACKNOWLEDGED,
    TRANSFER_REQUESTED,
    CONNECT_REQUESTED,
    CONNECT_COMPLETED,
    ARRIVAL_ATTESTED,
    FAILED
}
