package com.lkjmc.common.menu;

public final class MenuTypes {
    private MenuTypes() {}

    public enum RouteKind { STATIC, LIST, DETAIL, CONFIRM, CUSTOM }
    public enum Theme { ROOT, NETWORK, TRAVEL, CLAIMS, ECONOMY, SOCIAL, PROFILE,
        SETTINGS, STAFF, ADVENTURE, DANGER, DOCS }
    public enum Domain { LOCAL_DOCS, MENUS, PERMISSIONS, CLAIMS, SETTINGS,
        PROFILES, ROUTING, PRESENCE }
    public enum Scope { LOCAL, GLOBAL, PLAYER, NETWORK, SERVER }
    public enum Freshness { CURRENT, STALE, UNAVAILABLE }
    public enum Role { INFO, ACTION, NAVIGATION, DECORATION, DISABLED, SUCCESS, DANGER }
    public enum ActionType { NAVIGATE, BACK, CLOSE, REFRESH, NONE, MUTATION }
    public enum Failure {
        MALFORMED_BUNDLE, UNKNOWN_ROUTE, MISSING_PARAMETER, STALE_RENDER,
        STALE_RESPONSE, BUSY_SESSION, DEPENDENCY_UNAVAILABLE, DEPENDENCY_STALE,
        PERMISSION_DENIED, UNATTESTED, UNSUPPORTED_OPERATION, UNKNOWN_ACTION
    }
    public enum Operation {
        ADVENTURE_PARTY_START, ADVENTURE_START, CLAIM_CREATE, CLAIM_DELETE,
        COMMAND_HELP, DOCTOR_VIEW, HOME_DELETE, HOME_NAME_INPUT, HOME_SAVE,
        INSTANCE_CREATE, INSTANCE_DELETE, INSTANCE_RESTART, INSTANCE_STOP,
        LANGUAGE_SET_EN, LANGUAGE_SET_JA, PARTY_LEAVE, REPORT_RESOLVE,
        SERVER_NAME_INPUT, SHOP_PURCHASE, KIT_CLAIM, STATUS_VIEW
    }
    public enum Binding {
        ACHIEVEMENTS, ACHIEVEMENT_DETAIL, ACHIEVEMENT_DIRECTORY, ADMIN_AUDIT,
        ADMIN_CONFIG, ADMIN_ECONOMY, ADMIN_MODERATION, ADMIN_SECURITY,
        ADMIN_SERVERS, ADMIN_SERVER_CREATE_KIND, ADMIN_SERVER_CREATE_TEMPLATE,
        ADMIN_SERVER_DETAIL, ADMIN_WEB, ADVENTURES, CLAIMS, CLAIM_DETAIL,
        CLAIM_TRUST_PICKER, DAILY, DOCS_DIRECTORY, DOCS_FILE, DOCS_LINKS,
        DOCS_SEARCH, HOMES, HOME_DETAIL, KITS, MAIL, PARTY, PARTY_INVITE_PICKER,
        PROFILE, RANDOM_TELEPORT, REPORTS, REPORT_DETAIL, SERVER_LIST, SETTINGS,
        SHOP, TELEPORTS, TELEPORT_PICKER, VOTES, WARPS
    }
}
