#!/usr/bin/env python3
"""Generate the Rust include list for checked command-contract shards."""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMMANDS = ROOT / "contracts/commands"
INDEX = COMMANDS / "README.json"
OUTPUT = ROOT / "crates/lkjmc-core/src/command_shards.rs"


def load_index():
    try:
        index = json.loads(INDEX.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"{INDEX}: {error}") from error
    if set(index) != {"format", "shards"} or index["format"] != "lkjmc-command-shards-v1":
        raise ValueError(f"{INDEX}: invalid index")
    shards = index["shards"]
    if not isinstance(shards, list) or not shards or shards != sorted(shards):
        raise ValueError(f"{INDEX}: shards must be a nonempty sorted array")
    if any(not isinstance(name, str) or "/" in name or not name.endswith(".json") for name in shards):
        raise ValueError(f"{INDEX}: invalid shard name")
    return shards


def render(shards):
    lines = [
        "// Generated by scripts/generate-contracts.py; do not edit.",
        "pub const SOURCES: &[&str] = &[",
    ]
    for name in shards:
        lines.append(f'    include_str!("../../../contracts/commands/{name}"),')
    lines += ["];", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        rendered = render(load_index())
    except ValueError as error:
        print(error)
        return 1
    if args.check:
        if OUTPUT.is_file() and OUTPUT.read_text(encoding="utf-8") == rendered:
            print("ok generate-contracts")
            return 0
        print(f"{OUTPUT.relative_to(ROOT)}: run scripts/generate-contracts.py")
        return 1
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
