"""Exact Java projection of canonical Rust/PostgreSQL sync payload types."""
from collections import OrderedDict

# A trailing ? denotes a canonical JSON null. Maps are bounded string maps; the
# daemon currently gives metadata/privacy no narrower product schema.
RECORDS = OrderedDict([
    ("PermissionGrant", {"id": "UUID", "roleId": "String", "expiresAt": "Instant?"}),
    ("PermissionPayload", {"principalKind": "String", "principalId": "String",
                           "grants": "List<PermissionGrant>", "permissions": "List<String>"}),
    ("ClaimTrust", {"uuid": "UUID", "name": "String"}),
    ("ClaimChunk", {"claimId": "UUID", "ownerUuid": "UUID", "ownerName": "String",
                    "name": "String", "worldName": "String", "chunkX": "int",
                    "chunkZ": "int", "trusts": "List<ClaimTrust>"}),
    ("ClaimPayload", {"chunks": "List<ClaimChunk>"}),
    ("ShopItem", {"id": "String", "titleKey": "String", "pricePoints": "long",
                  "metadata": "Map<String,String>"}),
    ("KitItem", {"id": "String", "titleKey": "String", "rewardPoints": "long",
                 "cooldownHours": "long"}),
    ("VoteItem", {"id": "String", "titleKey": "String", "url": "String"}),
    ("PluginItem", {"id": "String", "displayName": "String", "platforms": "List<String>"}),
    ("MenuPayload", {"shop": "List<ShopItem>", "kits": "List<KitItem>",
                     "votes": "List<VoteItem>", "plugins": "List<PluginItem>"}),
    ("ProfileItem", {"material": "String", "amount": "int", "damage": "long",
                     "customName": "String?", "lore": "List<String>",
                     "enchantments": "List<Enchantment>", "customModelData": "Integer?"}),
    ("ProfileSlot", {"slot": "int", "item": "ProfileItem"}),
    ("Enchantment", {"id": "String", "level": "int"}),
    ("Experience", {"progress": "double", "level": "long", "total": "long"}),
    ("Vitals", {"health": "double", "food": "int", "saturation": "double", "air": "int"}),
    ("PotionEffect", {"id": "String", "amplifier": "int", "durationTicks": "long",
                      "ambient": "boolean", "particles": "boolean", "icon": "boolean"}),
    ("PluginDatum", {"key": "String", "value": "String"}),
    ("SavedLocation", {"name": "String", "server": "String", "world": "String",
                       "x": "double", "y": "double", "z": "double",
                       "yaw": "double", "pitch": "double"}),
    ("ProfileSettings", {"menuEnabled": "boolean", "hudEnabled": "boolean",
                         "tipsEnabled": "boolean", "privacy": "String"}),
    ("ProfileEnvelope", {"schema": "String", "inventory": "List<ProfileSlot>",
                         "armor": "List<ProfileSlot>", "offhand": "ProfileItem?",
                         "selectedHotbarSlot": "int", "enderChest": "List<ProfileSlot>",
                         "experience": "Experience", "vitals": "Vitals",
                         "potionEffects": "List<PotionEffect>", "gameMode": "GameMode?",
                         "pluginData": "List<PluginDatum>", "homes": "List<SavedLocation>",
                         "warps": "List<SavedLocation>", "points": "long",
                         "achievements": "List<String>", "settings": "ProfileSettings",
                         "language": "String"}),
    ("ProfileAvailable", {"playerUuid": "UUID", "scope": "String",
                          "profileRevision": "long", "schema": "String",
                          "sha256": "String", "envelope": "ProfileEnvelope"}),
    ("ProfileMissing", {"playerUuid": "UUID", "scope": "String"}),
    ("PresenceAvailable", {"instanceId": "String", "playerCount": "Integer?",
                           "maxPlayers": "Integer?", "ready": "boolean",
                           "lastHeartbeatAt": "Instant", "suspendReason": "String?"}),
    ("PresenceMissing", {"instanceId": "String"}),
    ("RoutingPort", {"port": "int", "purpose": "String"}),
    ("RoutingInstance", {"id": "String", "kind": "String", "desiredState": "String",
                         "observedState": "String?", "healthy": "Boolean?", "ready": "Boolean?",
                         "playerCount": "Integer?", "ports": "List<RoutingPort>"}),
    ("RoutingPayload", {"instances": "List<RoutingInstance>"}),
    ("SettingsPayload", {"playerUuid": "UUID", "language": "String",
                         "menuEnabled": "boolean", "hudEnabled": "boolean",
                         "tipsEnabled": "boolean", "privacy": "Map<String,String>"}),
    ("FeedChange", {"feedRevision": "long", "domain": "String", "key": "String",
                    "revision": "long"}),
    ("SyncErrorBody", {"code": "String"}),
])

PAYLOADS = OrderedDict([
    ("permissions", "PermissionPayload"), ("claims", "ClaimPayload"),
    ("menus", "MenuPayload"), ("profiles", "ProfilePayload"),
    ("presence", "PresencePayload"), ("routing", "RoutingPayload"),
    ("settings", "SettingsPayload"),
])

VARIANTS = {"ProfilePayload": ["ProfileAvailable", "ProfileMissing"],
            "PresencePayload": ["PresenceAvailable", "PresenceMissing"]}

PAYLOAD_KEYS = {
    "permissions": {"principalKind", "principalId", "grants", "id", "roleId", "expiresAt", "permissions"},
    "claims": {"chunks", "claimId", "ownerUuid", "ownerName", "name", "worldName", "chunkX", "chunkZ", "trusts", "uuid"},
    "menus": {"shop", "id", "titleKey", "pricePoints", "metadata", "kits", "rewardPoints", "cooldownHours", "votes", "url", "plugins", "displayName", "platforms"},
    "profiles": {"playerUuid", "scope", "profileRevision", "schema", "sha256", "envelope", "profile"},
    "presence": {"instanceId", "playerCount", "maxPlayers", "ready", "lastHeartbeatAt", "suspendReason", "available"},
    "routing": {"instances", "id", "kind", "desiredState", "observedState", "healthy", "ready", "playerCount", "ports", "port", "purpose"},
    "settings": {"playerUuid", "language", "menuEnabled", "hudEnabled", "tipsEnabled", "privacy"},
}
