//! Shared, language-independent first-party message envelopes.
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value, json};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemMessage {
    pub id: String,
    pub params: Map<String, Value>,
}
impl SystemMessage {
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into(), params: Map::new() }
    }
    pub fn with(mut self, name: impl Into<String>, value: impl Into<Value>) -> Self {
        self.params.insert(name.into(), value.into());
        self
    }
    pub fn unknown(diagnostic: impl std::fmt::Display) -> Self {
        let reference = uuid::Uuid::new_v4();
        tracing::warn!(%reference, diagnostic=%diagnostic, "unclassified system message");
        Self::new("system.unknown").with("reference", reference.to_string())
    }
    pub fn from_record(value: &Value, reference: &str) -> Value {
        let parsed = match value {
            Value::String(text) => serde_json::from_str(text).ok(),
            Value::Object(_) => Some(value.clone()),
            _ => None,
        };
        if let Some(parsed) = parsed {
            if serde_json::from_value::<Self>(parsed.clone()).is_ok() { return parsed; }
        }
        json!(Self::new("system.unknown").with("reference", reference))
    }
}
impl From<&str> for SystemMessage {
    fn from(value: &str) -> Self {
        // Authoring literals are migrated to IDs offline; prose is diagnostic only.
        if value.starts_with("text.") || value.starts_with("system.") || value.starts_with("error.") {
            Self::new(value)
        } else if let Ok(message) = serde_json::from_str(value) {
            message
        } else {
            Self::unknown(value)
        }
    }
}
impl From<String> for SystemMessage {
    fn from(value: String) -> Self { Self::from(value.as_str()) }
}
impl std::fmt::Display for SystemMessage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", serde_json::to_string(self).map_err(|_| std::fmt::Error)?)
    }
}

/// Project only known system-owned fields; user text and raw job output are untouched.
/// Call at the authenticated read boundary, after authorization and data selection.
pub fn project_system_content(value: &mut Value) {
    match value {
        Value::Array(items) => items.iter_mut().for_each(project_system_content),
        Value::Object(item) => {
            let system_record = item.contains_key("progress")
                || item.contains_key("observed")
                || item.get("kind").and_then(Value::as_str) == Some("job_finished")
                || item.contains_key("completed_at") && item.contains_key("manifest");
            let reference = item.get("id").map(|value| value.as_str().map(str::to_owned).unwrap_or_else(|| value.to_string())).unwrap_or_else(|| "system-record".into());
            if system_record {
                if let Some(error) = item.get_mut("error").filter(|v| !v.is_null()) {
                    *error = SystemMessage::from_record(error, &reference);
                }
                if let Some(progress) = item.get_mut("progress").and_then(Value::as_object_mut) {
                    if let Some(message) = progress.get_mut("message") {
                        *message = SystemMessage::from_record(message, &reference);
                    }
                }
            }
            // A job result's message is authored by a trusted adapter. Files and logs
            // remain their original text; only this explicitly owned slot is projected.
            if item.contains_key("progress") {
                if let Some(result) = item.get_mut("result").and_then(Value::as_object_mut) {
                    if let Some(message) = result.get_mut("message").filter(|v| !v.is_null()) {
                        *message = SystemMessage::from_record(message, &reference);
                    }
                }
            }
            // Notifications are generated by Core, whereas chat `body` is a string.
            if matches!(item.get("kind").and_then(Value::as_str), Some("job_finished" | "adventure_refund" | "expedition_refund")) {
                if let Some(body) = item.get_mut("body").and_then(Value::as_object_mut) {
                    for key in ["error", "message"] {
                        if let Some(text) = body.get_mut(key).filter(|v| !v.is_null()) {
                            *text = SystemMessage::from_record(text, &reference);
                        }
                    }
                }
            }
            // Do not descend into raw result/manifest, chat body, player profiles or custom titles.
            for (key, child) in item.iter_mut() {
                if !matches!(key.as_str(), "result" | "manifest" | "body" | "profile" | "title") {
                    project_system_content(child);
                }
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn messages_serialize_parameters_without_rendering() {
        let message = SystemMessage::new("error.internal").with("reference", "abc");
        assert_eq!(serde_json::to_value(message).unwrap(), json!({"id":"error.internal","params":{"reference":"abc"}}));
    }
    #[test]
    fn projection_keeps_player_text_and_raw_logs_and_classifies_only_system_fields() {
        let mut data = json!({"jobs":[{"id":"operation","progress":{"message":"日本語の診断"},"error":"failure","result":{"lines":["日本語のログ"]}}],"messages":[{"body":"日本語の会話"}],"assets":[{"title":"日本語の名前"}]});
        project_system_content(&mut data);
        assert_eq!(data["jobs"][0]["error"]["id"], "system.unknown");
        assert_eq!(data["jobs"][0]["progress"]["message"]["params"]["reference"], "operation");
        assert_eq!(data["jobs"][0]["result"]["lines"][0], "日本語のログ");
        assert_eq!(data["messages"][0]["body"], "日本語の会話");
        assert_eq!(data["assets"][0]["title"], "日本語の名前");
    }
}
